
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALTER COMMA CREATE CURRENT_TIMESTAMP DATABASE DEFAULT DELETE DOT DROP EQ FROM IDENTIFIER INSERT INT INTO KEY LPAREN NOT NULL PRIMARY PUBLIC RENAME RPAREN SELECT SEMICOLON SERIAL SET STAR STRING TABLE TIMESTAMP TO UPDATE VALUES VARCHAR WHEREstatement : CREATE DATABASE IDENTIFIER SEMICOLONstatement : DROP DATABASE IDENTIFIER SEMICOLONstatement : ALTER DATABASE IDENTIFIER RENAME TO IDENTIFIER SEMICOLONstatement : CREATE TABLE IDENTIFIER LPAREN columns RPAREN SEMICOLONcolumns : columns COMMA column\n               | columncolumn : IDENTIFIER SERIAL PRIMARY KEY\n              | IDENTIFIER VARCHAR LPAREN INT RPAREN NOT NULL\n              | IDENTIFIER VARCHAR LPAREN INT RPAREN\n              | IDENTIFIER TIMESTAMP DEFAULT CURRENT_TIMESTAMPstatement : DROP TABLE IDENTIFIER SEMICOLONstatement : ALTER TABLE IDENTIFIER RENAME TO IDENTIFIER SEMICOLONstatement : INSERT INTO IDENTIFIER LPAREN columns RPAREN VALUES LPAREN values RPAREN SEMICOLONvalues : values COMMA value\n              | valuevalue : INT\n             | STRINGstatement : UPDATE IDENTIFIER SET IDENTIFIER EQ STRING WHERE IDENTIFIER EQ INT SEMICOLONstatement : DELETE FROM IDENTIFIER WHERE IDENTIFIER EQ INT SEMICOLONstatement : SELECT STAR FROM PUBLIC DOT IDENTIFIER SEMICOLON'
    
_lr_action_items = {'CREATE':([0,],[2,]),'DROP':([0,],[3,]),'ALTER':([0,],[4,]),'INSERT':([0,],[5,]),'UPDATE':([0,],[6,]),'DELETE':([0,],[7,]),'SELECT':([0,],[8,]),'$end':([1,29,31,32,62,64,65,69,75,87,89,],[0,-1,-2,-11,-4,-3,-12,-20,-19,-13,-18,]),'DATABASE':([2,3,4,],[9,11,13,]),'TABLE':([2,3,4,],[10,12,14,]),'INTO':([5,],[15,]),'IDENTIFIER':([6,9,10,11,12,13,14,15,17,26,30,35,37,42,43,47,52,67,],[16,19,20,21,22,23,24,25,27,36,39,39,46,53,54,58,39,74,]),'FROM':([7,18,],[17,28,]),'STAR':([8,],[18,]),'SET':([16,],[26,]),'SEMICOLON':([19,21,22,51,53,54,58,68,83,85,],[29,31,32,62,64,65,69,75,87,89,]),'LPAREN':([20,25,49,66,],[30,35,60,73,]),'RENAME':([23,24,],[33,34,]),'WHERE':([27,56,],[37,67,]),'PUBLIC':([28,],[38,]),'TO':([33,34,],[42,43,]),'EQ':([36,46,74,],[45,57,81,]),'DOT':([38,],[47,]),'SERIAL':([39,],[48,]),'VARCHAR':([39,],[49,]),'TIMESTAMP':([39,],[50,]),'RPAREN':([40,41,44,63,70,71,72,76,77,78,79,80,86,88,],[51,-6,55,-5,-7,76,-10,-9,83,-15,-16,-17,-8,-14,]),'COMMA':([40,41,44,63,70,72,76,77,78,79,80,86,88,],[52,-6,52,-5,-7,-10,-9,84,-15,-16,-17,-8,-14,]),'STRING':([45,73,84,],[56,80,80,]),'PRIMARY':([48,],[59,]),'DEFAULT':([50,],[61,]),'VALUES':([55,],[66,]),'INT':([57,60,73,81,84,],[68,71,79,85,79,]),'KEY':([59,],[70,]),'CURRENT_TIMESTAMP':([61,],[72,]),'NOT':([76,],[82,]),'NULL':([82,],[86,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'columns':([30,35,],[40,44,]),'column':([30,35,52,],[41,41,63,]),'values':([73,],[77,]),'value':([73,84,],[78,88,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> CREATE DATABASE IDENTIFIER SEMICOLON','statement',4,'p_statement_create_database','parser.py',5),
  ('statement -> DROP DATABASE IDENTIFIER SEMICOLON','statement',4,'p_statement_drop_database','parser.py',9),
  ('statement -> ALTER DATABASE IDENTIFIER RENAME TO IDENTIFIER SEMICOLON','statement',7,'p_statement_alter_database','parser.py',13),
  ('statement -> CREATE TABLE IDENTIFIER LPAREN columns RPAREN SEMICOLON','statement',7,'p_statement_create_table','parser.py',17),
  ('columns -> columns COMMA column','columns',3,'p_columns','parser.py',21),
  ('columns -> column','columns',1,'p_columns','parser.py',22),
  ('column -> IDENTIFIER SERIAL PRIMARY KEY','column',4,'p_column','parser.py',29),
  ('column -> IDENTIFIER VARCHAR LPAREN INT RPAREN NOT NULL','column',7,'p_column','parser.py',30),
  ('column -> IDENTIFIER VARCHAR LPAREN INT RPAREN','column',5,'p_column','parser.py',31),
  ('column -> IDENTIFIER TIMESTAMP DEFAULT CURRENT_TIMESTAMP','column',4,'p_column','parser.py',32),
  ('statement -> DROP TABLE IDENTIFIER SEMICOLON','statement',4,'p_statement_drop_table','parser.py',36),
  ('statement -> ALTER TABLE IDENTIFIER RENAME TO IDENTIFIER SEMICOLON','statement',7,'p_statement_alter_table','parser.py',40),
  ('statement -> INSERT INTO IDENTIFIER LPAREN columns RPAREN VALUES LPAREN values RPAREN SEMICOLON','statement',11,'p_statement_insert','parser.py',44),
  ('values -> values COMMA value','values',3,'p_values','parser.py',48),
  ('values -> value','values',1,'p_values','parser.py',49),
  ('value -> INT','value',1,'p_value','parser.py',56),
  ('value -> STRING','value',1,'p_value','parser.py',57),
  ('statement -> UPDATE IDENTIFIER SET IDENTIFIER EQ STRING WHERE IDENTIFIER EQ INT SEMICOLON','statement',11,'p_statement_update','parser.py',61),
  ('statement -> DELETE FROM IDENTIFIER WHERE IDENTIFIER EQ INT SEMICOLON','statement',8,'p_statement_delete','parser.py',65),
  ('statement -> SELECT STAR FROM PUBLIC DOT IDENTIFIER SEMICOLON','statement',7,'p_statement_select','parser.py',69),
]
